FROM alpine:latest

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" > /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk update
RUN apk upgrade

RUN apk add lxd openrc

RUN rc-update add lxd
#RUN rc-service lxd start

RUN rc-update add cgroups
#RUN rc-service cgroups start

RUN echo "session optional pam_cgfs.so -c freezer,memory,name=systemd,unified" >> /etc/pam.d/system-login

RUN echo "lxc.idmap = u 0 100000 65536" >> /etc/lxc/default.conf
RUN echo "lxc.idmap = g 0 100000 65536" >> /etc/lxc/default.conf

RUN echo "root:100000:65536" >> /etc/subuid
RUN echo "root:100000:65536" >> /etc/subgid

#RUN lxd init
